/*
 * Self-host Noto Sans for the render, embedded as data: URIs.
 *
 * The client's scene asks for the brand typeface with
 *   font-family: '"Noto Sans", sans-serif'
 * and the Claude Design page loaded it from Google Fonts at this exact axis:
 *   ital,wght@0,400;0,500;0,700;0,800;0,900;1,700;1,900
 * All seven of those are really used — 500 and 800 appear in the menu lists and
 * the badge, italic 700 in the "Para ti" line. A weight that is merely missing
 * does not fail loudly: the browser synthesises a fake bold or oblique and the
 * type quietly changes shape.
 *
 * Two reasons the faces are inlined rather than linked:
 *
 *  1. A HyperFrames render must not fetch anything at render time.
 *  2. The client's own runtime (animations-v3.jsx → useInlineFontsInto) walks
 *     document.styleSheets on mount, downloads every @font-face url it finds,
 *     and re-inserts them as data URIs inside the scene. That is for Claude
 *     Design's SVG export, and it is asynchronous — a font re-resolving partway
 *     through a render is exactly the kind of frame-to-frame drift the render
 *     must not have. That routine skips any url that is already `data:`, so
 *     shipping the faces pre-inlined turns it into a no-op instead of editing
 *     a line of the client's code.
 *
 *   node scripts/build-fonts.mjs
 *
 * Latin and Latin-Extended only: the board is Spanish and English. Same idea as
 * tv-menu/motion/hyperframes/scripts/build-brand-css.py, which self-hosts the
 * same typeface for the Menu Items Motion video.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PROJECT = join(HERE, "..");

// A modern browser UA, or Google serves the ttf fallback instead of woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const AXIS = "ital,wght@0,400;0,500;0,700;0,800;0,900;1,700;1,900";
const CSS_URL = `https://fonts.googleapis.com/css2?family=Noto+Sans:${AXIS}&display=block`;
const KEEP = new Set(["latin", "latin-ext"]);

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

const blocks = css.split("@font-face").slice(1);
const faces = [];

for (const block of blocks) {
  const subset = (block.match(/\/\*\s*([a-z0-9-]+)\s*\*\//) || [, "?"])[1];
  if (!KEEP.has(subset)) continue;

  const style = (block.match(/font-style:\s*(\w+)/) || [, "normal"])[1];
  const weight = (block.match(/font-weight:\s*(\d+)/) || [, "400"])[1];
  const src = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
  if (!src) continue;

  const bytes = Buffer.from(
    await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer()
  );
  faces.push({ style, weight, subset, range, b64: bytes.toString("base64") });
}

const out = [
  "/* GENERATED by scripts/build-fonts.mjs — do not edit.",
  ` * Noto Sans, axis ${AXIS}, latin + latin-ext.`,
  " * Faces are embedded so the render fetches nothing and so the scene's own",
  " * font-inlining pass has nothing left to do. See the script header.",
  " */",
  "",
  ...faces.map((f) =>
    [
      "@font-face {",
      "  font-family: 'Noto Sans';",
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      "  font-display: block;",
      `  src: url("data:font/woff2;base64,${f.b64}") format('woff2');`,
      f.range ? `  unicode-range: ${f.range};` : null,
      "}",
    ]
      .filter(Boolean)
      .join("\n")
  ),
  "",
].join("\n");

mkdirSync(join(PROJECT, "assets"), { recursive: true });
writeFileSync(join(PROJECT, "assets", "fonts.css"), out);

console.log(`${faces.length} faces embedded`);
for (const f of faces) console.log(`  ${f.style} ${f.weight} ${f.subset}`);
